# Even Fibonacci Numbers
# Problem 2

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fib(n):
    """ Generates fibonacci sequence up to n """
    fib = []
    
    a, b = 1, 2
    fib.append(a)
    fib.append(b)
    while a <= n and b <= n:
        a = a + b
        b = b + a
        fib.append(a)
        fib.append(b)
    

    evenfib = []
    for i in fib:
        if i % 2 == 0:
            evenfib.append(i)
    return sum(evenfib)
        
print(fib(4000000))
